# Generated by Django 4.2.6 on 2023-11-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_s_no_todo_sno_rename_status_todo_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todo',
            name='sno',
            field=models.IntegerField(null=True),
        ),
    ]
