# Generated by Django 4.2.6 on 2023-11-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todo_id_alter_todo_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='sno',
        ),
    ]
