# Generated by Django 4.2.6 on 2023-11-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_remove_todo_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='sno',
            field=models.IntegerField(null=True),
        ),
    ]
